steps:
- name: python:3.9
  entrypoint: python
  args: ["pip3", "install", "-r", "requirements.txt", "--user"]
  
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  env:
    - 'DB_STRING=${_DB_STRING}'
    - 'SECRET_KEY=${_SECRET_KEY}'
    - 'GS_BUCKET_NAME=${_GS_BUCKET_NAME}'
timeout: "1700s"