# Generated by Django 3.0 on 2019-12-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_dias', models.IntegerField(choices=[(15, 'Quinze dias'), (30, 'Trinta dias')])),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='LicencaPremio',
            fields=[
                ('ferias_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ferias')),
            ],
            options={
                'verbose_name': 'Licenças Prêmio',
                'verbose_name_plural': 'Licença Prêmio',
            },
            bases=('app.ferias',),
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('data_admissao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Setor')),
            ],
            options={
                'verbose_name_plural': 'Trabalhadores',
            },
        ),
        migrations.AddField(
            model_name='ferias',
            name='trabalhador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trabalhador'),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trabalhador')),
            ],
        ),
    ]
