# Generated by Django 3.0.5 on 2021-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
