# Generated by Django 3.0.5 on 2021-05-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='trabalhador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Trabalhador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ferias',
            name='trabalhador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Trabalhador'),
            preserve_default=False,
        ),
    ]
