# Generated by Django 2.2.4 on 2019-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhador',
            name='situacao',
            field=models.CharField(choices=[('ferias', 'Férias'), ('licenca', 'Licença-prêmio'), ('abono', 'Abono'), ('ativo', 'Ativo'), ('atestado', 'Atestado Médico')], default='ativo', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_termino',
            field=models.DateTimeField(editable=False),
        ),
    ]
