# Generated by Django 2.2.4 on 2019-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='deferido',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ferias',
            name='deferida',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
