# Generated by Django 3.0.5 on 2021-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210519_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateField(),
        ),
    ]
