# Generated by Django 2.2.4 on 2019-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191216_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_termino',
            field=models.DateField(editable=False),
        ),
    ]
