# Generated by Django 2.2.4 on 2019-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191216_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
