# Generated by Django 2.2.4 on 2019-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191216_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='observacoes',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='observacoes',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
