# Generated by Django 3.0.5 on 2021-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210520_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
