# Generated by Django 3.0.5 on 2021-05-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210520_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
