# Generated by Django 3.0.5 on 2021-05-20 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210520_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
