# Generated by Django 2.2.4 on 2020-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ferias_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='fruido',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ferias',
            name='fruida',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='trabalhador',
            name='matricula',
            field=models.CharField(default='00000-0', max_length=15),
            preserve_default=False,
        ),
    ]
