# Generated by Django 3.0.5 on 2021-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210520_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
