# Generated by Django 2.2.4 on 2020-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200122_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abono',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='ferias',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Férias', 'verbose_name_plural': 'Férias'},
        ),
        migrations.AlterModelOptions(
            name='licencapremio',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Licenças Prêmio', 'verbose_name_plural': 'Licença Prêmio'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='trabalhador',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Trabalhadores'},
        ),
        migrations.AlterField(
            model_name='trabalhador',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
