# Generated by Django 2.2.4 on 2020-01-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200131_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
