# Generated by Django 3.0.5 on 2021-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210730_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefedesetor',
            name='rg',
            field=models.CharField(default='12.123.123-1', max_length=20),
            preserve_default=False,
        ),
    ]
