# Generated by Django 3.0.5 on 2021-08-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chefedesetor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
