# Generated by Django 2.2.4 on 2020-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='qtd_dias',
            field=models.IntegerField(choices=[(14, 'Quinze dias'), (29, 'Trinta dias')]),
        ),
    ]
