# Generated by Django 2.2.4 on 2020-06-22 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200622_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
