# Generated by Django 2.2.4 on 2020-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200622_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linharelatorio',
            options={'ordering': ['id'], 'verbose_name': 'Linha de Relatório', 'verbose_name_plural': 'Linhas de Relatório'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AddField(
            model_name='relatorio',
            name='estado',
            field=models.CharField(default='vazio', max_length=100),
        ),
    ]
