# Generated by Django 2.2.4 on 2020-06-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200622_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='linhas',
            field=models.ManyToManyField(blank=True, to='app.LinhaRelatorio'),
        ),
    ]
