# Generated by Django 2.2.4 on 2020-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200622_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-criado_em', 'setor__nome'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AddField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
