# Generated by Django 2.2.4 on 2020-06-22 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200622_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='ano',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
