# Generated by Django 2.2.4 on 2020-06-23 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200622_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='num_oficio',
            field=models.IntegerField(default=666, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
