# Generated by Django 2.2.4 on 2020-07-09 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_relatorio_num_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
