# Generated by Django 2.2.4 on 2020-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200709_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='num_oficio',
            field=models.CharField(max_length=10),
        ),
    ]
