# Generated by Django 2.2.4 on 2020-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200714_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhador',
            name='registro',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
