# Generated by Django 2.2.4 on 2020-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_trabalhador_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='registro',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
