# Generated by Django 2.2.14 on 2020-07-17 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200714_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='data_fechamento',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
