# Generated by Django 2.2.14 on 2020-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_trabalhador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
