# Generated by Django 2.2.14 on 2020-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200720_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhador',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalhador',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalhador',
            name='ctps_serie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trabalhador',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
