# Generated by Django 2.2.14 on 2020-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200723_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='mostrado_esse_mes',
            field=models.BooleanField(default=False),
        ),
    ]
