# Generated by Django 2.2.14 on 2020-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_lembrete_mostrado_esse_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proximas_folgas', models.BooleanField(default=True, help_text='Mostra uma tabela na página principal, representando os trabalhadores que tem as folgas próximas')),
                ('em_andamento', models.BooleanField(default=True, help_text='Mostra uma tabela na página principal, representando os trabalhadores que estão de folga no momento')),
                ('proximos_retornos', models.BooleanField(default=True, help_text='Mostra uma tabela na página principal, representando os trabalhadores que estão no final de sua folga ')),
                ('previa_de_impressao', models.BooleanField(default=True, help_text='Mostra a prévia do arquivo a ser impresso ou não')),
                ('calculo_de_adicional', models.BooleanField(default=False, help_text='Multiplica o total de horas por 1,143, caso marcado')),
                ('cards_colapsados', models.BooleanField(default=False, help_text='Exibe tabelas e relações de forma colapsada, exibindo um botão para exibição dos dados')),
            ],
        ),
    ]
