# Generated by Django 2.2.14 on 2020-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='previa_de_impressao',
        ),
        migrations.AlterField(
            model_name='conf',
            name='calculo_de_adicional',
            field=models.BooleanField(default=False, help_text='Multiplica o total de horas por 1,143, caso marcado', verbose_name='Cálculo de Adicional Noturno'),
        ),
    ]
