# Generated by Django 2.2.14 on 2020-09-14 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200912_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='periodicidade',
            field=models.CharField(choices=[('d', 'Diário'), ('s', 'Semanal'), ('m', 'Mensal')], default='m', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='dia',
            field=models.IntegerField(help_text='Semanal: indique o dia da semana(0=segunda...). Mensal: caso não haja tal dia em algum mês(30, 31), o lembrete será exibido no último dia do mês', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
