# Generated by Django 2.2.14 on 2020-09-14 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200914_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembrete',
            name='dia',
            field=models.IntegerField(help_text='Semanal: indique o dia da semana(0=domingo, 1=segunda,...). Mensal: caso não haja tal dia em algum mês(30, 31), o lembrete será exibido no último dia do mês', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.CreateModel(
            name='RelacaoAbono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2020)])),
                ('mes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('semana', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('abonos', models.ManyToManyField(to='app.Abono')),
            ],
            options={
                'verbose_name': 'Relação de abonos',
                'verbose_name_plural': 'Relações de abonos',
                'ordering': ['-semana', '-mes', '-ano'],
            },
        ),
    ]
