# Generated by Django 2.2.14 on 2020-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200914_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacaoabono',
            options={'ordering': ['-semana', '-ano'], 'verbose_name': 'Relação de abonos', 'verbose_name_plural': 'Relações de abonos'},
        ),
        migrations.RemoveField(
            model_name='relacaoabono',
            name='mes',
        ),
        migrations.AlterField(
            model_name='relacaoabono',
            name='abonos',
            field=models.ManyToManyField(blank=True, to='app.Abono'),
        ),
    ]
