# Generated by Django 2.2.14 on 2020-09-16 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20200914_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacaoabono',
            name='semana',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(54), django.core.validators.MinValueValidator(1)]),
        ),
    ]
