# Generated by Django 2.2.14 on 2020-10-07 13:03

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200916_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relacaoabono',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Relação de abonos', 'verbose_name_plural': 'Relações de abonos'},
        ),
        migrations.RemoveField(
            model_name='relacaoabono',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='relacaoabono',
            name='semana',
        ),
        migrations.AddField(
            model_name='relacaoabono',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 3, 11, 281463, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacaoabono',
            name='data_termino',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 13, 3, 18, 737505, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
