# Generated by Django 2.2.14 on 2020-11-12 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20201007_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='expedientes',
            field=models.CharField(choices=[('m', 'Matutino'), ('v', 'Vespertino'), ('i', 'Integral')], default='i', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
