# Generated by Django 2.2.14 on 2020-11-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20201112_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abono',
            old_name='expedientes',
            new_name='expediente',
        ),
    ]
