# Generated by Django 2.2.14 on 2021-02-27 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210118_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='ano',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(2021)]),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
