# Generated by Django 2.2.14 on 2021-04-28 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20210227_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
