# Generated by Django 3.2 on 2021-05-02 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210428_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
